name: Generate stable API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: 'main'

    - name: Generate	    
      uses: docker://openapitools/openapi-generator-cli:latest-release
      with:
        args: >-
          generate -i https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/HNpQuMfIXMGlbdZVKjRucsFO
          -g swift5
          --additional-properties=library=alamofire,useSPMFileStructure=true
          -o /github/workspace

    # "echo" in commit returns true so the build succeeds, even if no changed files
    - name: Commit new changes to the repo
      if: ${{ steps.diff.outputs.count }} > 0
      run: |
        git config user.name jellyfin-bot
        git config user.email team@jellyfin.org
        git pull
        git add .
        git commit -m "Update stable OpenAPI client" || echo
        git push
