name: Generate stable API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: 'main'

    - name: Generate	    
      uses: docker://openapitools/openapi-generator-cli:latest
      with:
        args: >-
          generate -i api.json
          -g swift5 
          --additional-properties=projectName=JellyfinAPI,responseAs=Combine,library=vapor,useSPMFileStructure=true 
          -o /github/workspace
          -t templates/swift5/
          --type-mappings UUID=String

    # "echo" in commit returns true so the build succeeds, even if no changed files
    - name: Commit new changes to the repo
      run: |
        git config user.name jellyfin-bot
        git config user.email team@jellyfin.org
        git pull
        git add .
        git commit -m "Update stable OpenAPI client" || echo
        git push
